services:
  - type: web
    name: churn-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
